# ============================================================
# Transcriptomics Case Studies
# Case Study: GSE25014
# Technology: Microarray
# ============================================================
#
# Lesson 01
# Downloading GSE25014 from GEO
#
# Script:
# 01_download_data.R
#
# Dataset:
# GSE25014 - Heme Effects on Pulmonary Endothelial Cells
#
# Platform:
# GPL570 - Affymetrix Human Genome U133 Plus 2.0 Array
#
# Samples:
# 24
#
# Organism:
# Homo sapiens
#
# ============================================================


# ============================================================
# Lesson Objectives
# ============================================================
#
# In this lesson you will learn:
#
# • How to download a microarray dataset from GEO
# • What an ExpressionSet is
# • How to access expression data with exprs()
# • How to access sample metadata with pData()
# • How to access probe annotation with fData()
# • How to inspect the structure of a microarray dataset
# • How to organize data for a reproducible project
# • How to save raw and processed information locally
#
# ============================================================


# ============================================================
# Project Structure
# ============================================================
#
# This case study is organized as:
#
# GSE25014_Microarray/
#
# ├── README.md
# ├── scripts/
# ├── data/
# │   ├── raw/
# │   ├── metadata/
# │   └── processed/
# ├── figures/
# └── results/
#
# ============================================================


# ============================================================
# 0. Install Required Packages
# ============================================================

# Install BiocManager if necessary
if (!requireNamespace("BiocManager", quietly = TRUE)) {
  install.packages("BiocManager")}

# Install GEOquery
if (!requireNamespace("GEOquery", quietly = TRUE)) {
  BiocManager::install("GEOquery")}

# Install Biobase
if (!requireNamespace("Biobase", quietly = TRUE)) {
  BiocManager::install("Biobase")}

# Install tidyverse
if (!requireNamespace("tidyverse", quietly = TRUE)) {
  install.packages("tidyverse")}


# ============================================================
# 1. Load Libraries
# ============================================================

library(GEOquery)
library(Biobase)
library(tidyverse)


# ============================================================
# 2. Define Case Study Directory
# ============================================================

# The script belongs to:
#
# GSE25014_Microarray/scripts/
#
# Data generated by this case study will be stored inside:
#
# GSE25014_Microarray/data/
#
# GSE25014_Microarray/results/

case_study_dir <- "GSE25014_Microarray"


# Check whether the script is being executed from the
# repository root.

if (!dir.exists(case_study_dir)) {
  
  # If the case study directory does not exist,
  # assume the current working directory is already
  # GSE25014_Microarray.
  
  case_study_dir <- "."
  
}


# Display working case-study directory

cat("Case study directory:\n")
print(normalizePath(case_study_dir))


# ============================================================
# 3. Create Directory Structure
# ============================================================

raw_dir <- file.path(
  case_study_dir,
  "data",
  "raw",
  "GSE25014"
)

metadata_dir <- file.path(
  case_study_dir,
  "data",
  "metadata"
)

processed_dir <- file.path(
  case_study_dir,
  "data",
  "processed"
)

figures_dir <- file.path(
  case_study_dir,
  "figures"
)

results_dir <- file.path(
  case_study_dir,
  "results"
)


# Create directories

dir.create(
  raw_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

dir.create(
  metadata_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

dir.create(
  processed_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

dir.create(
  figures_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

dir.create(
  results_dir,
  recursive = TRUE,
  showWarnings = FALSE
)


cat("\n✓ Project directories created.\n")


# ============================================================
# 4. Download GSE25014 from GEO
# ============================================================

cat("\n")
cat("============================================================\n")
cat("Downloading GSE25014 from GEO\n")
cat("============================================================\n")


# Download the GEO dataset.
#
# GSEMatrix = TRUE
# → download the processed expression matrix
#
# AnnotGPL = TRUE
# → include GPL annotation information
#
# getGPL = TRUE
# → retrieve the platform information

gse <- getGEO(
  GEO = "GSE25014",
  GSEMatrix = TRUE,
  AnnotGPL = TRUE,
  getGPL = TRUE
)


# ============================================================
# 5. Select the ExpressionSet
# ============================================================

# getGEO() can return a list when a GEO accession
# contains more than one platform.

if (is.list(gse)) {
  eset <- gse[[1]]
} else {
  eset <- gse
}


cat("\n✓ ExpressionSet successfully loaded.\n\n")


# Display the ExpressionSet
print(eset)


# ============================================================
# 6. Understand the ExpressionSet
# ============================================================

# An ExpressionSet is a Bioconductor object designed
# to organize high-throughput biological data.
#
# It contains several types of information.
#
#
# Expression data:
#
# exprs(eset)
#
#         ↓
#
# Probes × Samples
#
#
# Sample metadata:
#
# pData(eset)
#
#         ↓
#
# Samples × Variables
#
#
# Feature annotation:
#
# fData(eset)
#
#         ↓
#
# Probes × Annotation
#
# ============================================================


# ============================================================
# 7. Inspect Dataset Dimensions
# ============================================================

cat("\n")
cat("============================================================\n")
cat("Dataset Dimensions\n")
cat("============================================================\n")

dataset_dimensions <- dim(eset)
cat("Features (probes):", dataset_dimensions[1], "\n")
cat("Samples:", dataset_dimensions[2], "\n")


# ============================================================
# 8. Extract Expression Matrix
# ============================================================

expr_matrix <- exprs(eset)


cat("\n")
cat("Expression matrix dimensions:\n")

print(dim(expr_matrix))


cat("\nFirst rows of expression matrix:\n")

print(head(expr_matrix[, 1:5]))


# ============================================================
# 9. Inspect Expression Values
# ============================================================

cat("\n")
cat("Expression matrix class:\n")

print(class(expr_matrix))


cat("\nExpression summary:\n")

print(summary(as.vector(expr_matrix)))


# Check missing values
missing_values <- sum(is.na(expr_matrix))

cat("\nMissing values:", missing_values, "\n")


# ============================================================
# 10. Extract Sample Metadata
# ============================================================

pdata <- pData(eset)


# Convert to data frame

metadata <- pdata %>%
  as.data.frame() %>%
  rownames_to_column(
    var = "SampleID"
  )


cat("\n")
cat("============================================================\n")
cat("Sample Metadata\n")
cat("============================================================\n")


cat(  "\nMetadata dimensions:\n")

print(dim(metadata))


cat("\nMetadata columns:\n")

print(colnames(metadata))


cat("\nFirst samples:\n")

print(head(metadata))


# ============================================================
# 11. Inspect Sample Titles
# ============================================================

cat("\n")
cat("Sample titles:\n")

print(metadata$title)


# Display unique sample descriptions

cat("\n")
cat("Unique sample titles:\n")

print(unique(metadata$title))


# ============================================================
# 12. Extract Probe Annotation
# ============================================================

fdata <- fData(eset)


cat("\n")
cat("============================================================\n")
cat("Probe Annotation\n")
cat("============================================================\n")


cat("\nAnnotation dimensions:\n")

print(dim(fdata))


cat("\nAvailable annotation columns:\n")

print(colnames(fdata))


cat("\nFirst annotation records:\n")

print(head(fdata))


# ============================================================
# 13. Create Clean Annotation Table
# ============================================================

annotations <- fdata %>%
  as.data.frame() %>%
  rownames_to_column(
    var = "ProbeID"
  )


# Check whether expected annotation columns exist

if ("Gene symbol" %in% colnames(annotations)) {
  annotations <- annotations %>%
    select(
      ProbeID,
      `Gene symbol`,
      `Gene title`,
      everything()
    )
}


cat("\n")
cat("Clean annotation table:\n")

print(head(annotations))


# ============================================================
# 14. Count Probes with Gene Annotation
# ============================================================

if ("Gene symbol" %in% colnames(annotations)) {
  probes_with_symbol <- sum(
    !is.na(annotations$`Gene symbol`) &
      annotations$`Gene symbol` != ""
  )
} else {
  probes_with_symbol <- NA
}


cat("\nProbes with gene symbols:", probes_with_symbol, "\n")


# ============================================================
# 15. Inspect Platform Information
# ============================================================

cat("\n")
cat("============================================================\n")
cat("Platform Information\n")
cat("============================================================\n")


cat("\nPlatform:\n")

print(annotation(eset))


cat("\nOrganism:\n")

print(organism(eset))


# ============================================================
# 16. Save Expression Matrix
# ============================================================

write.csv(
  expr_matrix,
  file = file.path(
    raw_dir,
    "expr_matrix_rma.csv"
  )
)


cat(
  "\n✓ Expression matrix saved.\n"
)


# ============================================================
# 17. Save Sample Metadata
# ============================================================

write.csv(
  metadata,
  file = file.path(
    raw_dir,
    "metadata.csv"
  ),
  row.names = FALSE
)


cat(
  "✓ Sample metadata saved.\n"
)


# ============================================================
# 18. Save Probe Annotation
# ============================================================

write.csv(
  annotations,
  file = file.path(
    raw_dir,
    "probe_annotations.csv"
  ),
  row.names = FALSE
)


cat(
  "✓ Probe annotation saved.\n"
)


# ============================================================
# 19. Save ExpressionSet Object
# ============================================================

saveRDS(
  eset,
  file = file.path(
    raw_dir,
    "eset_GSE25014.rds"
  )
)


cat(
  "✓ ExpressionSet saved.\n"
)


# ============================================================
# 20. Create Download Summary
# ============================================================

cat("\n")
cat("============================================================\n")
cat("GSE25014 DOWNLOAD SUMMARY\n")
cat("============================================================\n")


cat("\nDataset: GSE25014\n")

cat("Technology: Affymetrix Microarray\n")

cat("Platform: GPL570\n")

cat("Organism: Homo sapiens\n")

cat("Probes:", nrow(expr_matrix), "\n")

cat("Samples:", ncol(expr_matrix), "\n")

cat("Expression range:", round(min(expr_matrix), 2), "-", 
    round(max(expr_matrix), 2), "\n")

cat("Missing values:", missing_values, "\n")

cat("Probes with gene symbols:", probes_with_symbol, "\n")


# ============================================================
# 21. Data Quality Check
# ============================================================

cat("\n")
cat("============================================================\n")
cat("DATA QUALITY CHECK\n")
cat("============================================================\n")


if (
  nrow(expr_matrix) > 0 &&
  ncol(expr_matrix) > 0
) {
  
  cat("✓ GEO download successful.\n")
  cat("✓ Expression matrix available.\n")
  cat("✓ Sample metadata available.\n")
  cat("✓ Probe annotation available.\n")
  cat("✓ ExpressionSet object available.\n")
  
} else {
  
  cat("✗ Dataset download failed.\n")
  
}


# ============================================================
# 22. Files Created
# ============================================================

cat("\n")
cat("Files created:\n")

cat(
  "  - data/raw/GSE25014/expr_matrix_rma.csv\n"
)

cat(
  "  - data/raw/GSE25014/metadata.csv\n"
)

cat(
  "  - data/raw/GSE25014/probe_annotations.csv\n"
)

cat(
  "  - data/raw/GSE25014/eset_GSE25014.rds\n"
)


# ============================================================
# Lesson Summary
# ============================================================
#
# Today you learned:
#
# ✓ How to download a microarray dataset from GEO
#
# ✓ What an ExpressionSet is
#
# ✓ How to access expression data with exprs()
#
# ✓ How to access sample metadata with pData()
#
# ✓ How to access probe annotation with fData()
#
# ✓ How to inspect a microarray expression matrix
#
# ✓ How to inspect probe annotation
#
# ✓ How to organize a reproducible project
#
# ✓ How to save data locally
#
# ============================================================


# ============================================================
# Thinking Like a Bioinformatician
# ============================================================
#
# A transcriptomic dataset is not just an expression matrix.
#
# In a microarray experiment, we need to understand at least
# three interconnected layers:
#
#
# 1. Expression
#
# Probe × Sample
#
#
# 2. Metadata
#
# Sample × Experimental variables
#
#
# 3. Annotation
#
# Probe × Biological information
#
#
# These three components will be connected throughout
# the following lessons.
#
#
# One of the main challenges of microarray analysis is:
#
#
#        PROBE
#          ↓
#      annotation
#          ↓
#         GENE
#
#
# A single gene can be represented by multiple probes.
#
# Therefore, before performing gene-level analyses,
# we need to understand how probes are mapped to genes
# and how multiple probes should be handled.
#
# This will be the focus of upcoming lessons.
#
# ============================================================


# ============================================================
# Challenge
# ============================================================
#
# 1. How many probes are present in the dataset?
#
# 2. How many samples are present?
#
# 3. What platform was used?
#
# 4. What is the range of expression values?
#
# 5. Are there missing values?
#
# 6. How many probes have a gene symbol?
#
# 7. How many annotation columns are available?
#
# 8. What information can be found in pData()?
#
# 9. What information can be found in fData()?
#
# 10. What is the difference between a probe and a gene?
#
# ============================================================


# ============================================================
# End of Lesson 01
# ============================================================